__all__ = ['create_collection',
           'upload_document',
           'download_document',
           'search_collection',
           'inspect_catalog',
           'inspect_collection',
           'inspect_document',
           'delete_document',
           'delete_collection',
           'rename_collection',
           'rename_document',
           'update_collection',
           'update_document']